modLoader="javafml"
loaderVersion="[4,)"
license="Academic Free License v3.0"

[[mods]]
modId="inside_the_system"
version="1.2.0"
displayName="Inside the system"
displayURL="https://www.youtube.com/@DregIrWhat"
credits="Hi, I don't remember how I got here, but I think we'll have a good time together!!!!"
authors="DregIr"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.inside_the_system]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.65,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.inside_the_system]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration